In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Project DA 2\Ecommerce Sales.xlsx")

In [49]:
df.head()

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,Selling_Price,Discount,Payment_Method,Order_Status,Delivered_Date
0,ORD7002,30-06-2025,Anaya,anaya78@gmail.com,9.033946e+09,Jaipur,Rajasthan,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD7003,03-02-2025,Arjun,arjun69@gmail.com,9.626585e+09,Mumbai,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD7004,06-05-2025,Kavya,kavya92@gmail.com,9.118380e+09,Chennai,Tamil Nadu,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD7005,20-01-2025,Rahul,rahul38@gmail.com,9.444531e+09,Kolkata,West Bengal,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD7006,02-04-2025,Anaya,anaya51@gmail.com,9.183586e+09,Chennai,Tamil Nadu,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  524 non-null    str
 1   Purchase_Date   524 non-null    str
 2   Buyer_Name      524 non-null    str
 3   Email           524 non-null    str
 4   Phone           502 non-null    float64
 5   City            524 non-null    str
 6   State           524 non-null    str
 7   Item_Name       524 non-null    str
 8   Category        524 non-null    str
 9   Quantity        457 non-null    float64
 10  Selling_Price   471 non-null    float64
 11  Discount        455 non-null    object
 12  Payment_Method  524 non-null    str
 13  Order_Status    524 non-null    str
 14  Delivered_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 61.5+ KB

In [51]:
df.describe()

              Phone    Quantity  Selling_Price
count  5.020000e+02  457.000000     471.000000
mean   9.492228e+09    2.800875    3168.639066
std    2.931222e+08    1.963974    2969.682209
min    9.000892e+09   -1.000000     499.000000
25%    9.237546e+09    1.000000     999.000000
50%    9.492906e+09    3.000000    1999.000000
75%    9.743276e+09    5.000000    4999.000000
max    9.998564e+09    5.000000    9999.000000

In [52]:
df.shape

(524, 15)

In [53]:
df.isnull().sum()

Transaction_ID     0
Purchase_Date      0
Buyer_Name         0
Email              0
Phone             22
City               0
State              0
Item_Name          0
Category           0
Quantity          67
Selling_Price     53
Discount          69
Payment_Method     0
Order_Status       0
Delivered_Date    21
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.replace(['N/A','NULL',''],np.nan,inplace=True)

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,Selling_Price,Discount,Payment_Method,Order_Status,Delivered_Date
0,ORD7002,30-06-2025,Anaya,anaya78@gmail.com,9.033946e+09,Jaipur,Rajasthan,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD7003,03-02-2025,Arjun,arjun69@gmail.com,9.626585e+09,Mumbai,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD7004,06-05-2025,Kavya,kavya92@gmail.com,9.118380e+09,Chennai,Tamil Nadu,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD7005,20-01-2025,Rahul,rahul38@gmail.com,9.444531e+09,Kolkata,West Bengal,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD7006,02-04-2025,Anaya,anaya51@gmail.com,9.183586e+09,Chennai,Tamil Nadu,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD7521,17-02-2025,Vihaan,vihaan69@gmail.com,9.365148e+09,Bengaluru,Karnataka,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD7522,2025/03/21,Riya,riya63@gmail.com,9.275317e+09,Jaipur,Rajasthan,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD7523,10-04-2025,Arjun,arjun38@gmail.com,9.897674e+09,Kolkata,West Bengal,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD7524,11-01-2025,Vihaan,vihaan72@gmail.com,9.502522e+09,Lucknow,Uttar Pradesh,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD7525,03-03-2025,Arjun,arjun84@gmail.com,9.554909e+09,Chennai,Tamil Nadu,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [56]:
df=df.apply(lambda x: x.str.strip() if x.dtype =='str' else x)
df.head()

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,Selling_Price,Discount,Payment_Method,Order_Status,Delivered_Date
0,ORD7002,30-06-2025,Anaya,anaya78@gmail.com,9.033946e+09,Jaipur,Rajasthan,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD7003,03-02-2025,Arjun,arjun69@gmail.com,9.626585e+09,Mumbai,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD7004,06-05-2025,Kavya,kavya92@gmail.com,9.118380e+09,Chennai,Tamil Nadu,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD7005,20-01-2025,Rahul,rahul38@gmail.com,9.444531e+09,Kolkata,West Bengal,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD7006,02-04-2025,Anaya,anaya51@gmail.com,9.183586e+09,Chennai,Tamil Nadu,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [57]:
df['Buyer_Name'] = df['Buyer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()

In [58]:
df = df[df['Email'].str.contains('@',na=False)]

In [59]:
df['Purchase_Date']=pd.to_datetime(df['Purchase_Date'],errors='coerce')
df['Delivered_Date']=pd.to_datetime(df['Delivered_Date'],errors='coerce')

C:\Users\HP\AppData\Local\Temp\ipykernel_14016\386158741.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Purchase_Date']=pd.to_datetime(df['Purchase_Date'],errors='coerce')

In [60]:
cols=['Quantity','Selling_Price','Discount']

for c in cols:
    df[c] = pd.to_numeric(df[c],errors='coerce')

In [61]:
df = df[df['Quantity']>0]

In [62]:
df['Discount']=df['Discount'].fillna(0)
df['Phone']=df['Phone'].fillna('Unknown')
df['Delivered_Date']=df['Delivered_Date'].fillna(df['Purchase_Date'])

In [63]:
df.head()

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,Selling_Price,Discount,Payment_Method,Order_Status,Delivered_Date
0,ORD7002,2025-06-30,Anaya,anaya78@gmail.com,9033946351.0,Jaipur,Rajasthan,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07
1,ORD7003,2025-02-03,Arjun,arjun69@gmail.com,9626584853.0,Mumbai,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02
2,ORD7004,2025-05-06,Kavya,kavya92@gmail.com,9118379502.0,Chennai,Tamil Nadu,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05
5,ORD7007,2025-02-10,Kabir,kabir56@gmail.com,9676233869.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10
6,ORD7008,2025-02-17,Aditya,aditya69@gmail.com,9925677930.0,Hyderabad,Telangana,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17

In [64]:
df['Sales']=df['Quantity']*df['Selling_Price']

In [65]:
df

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,Selling_Price,Discount,Payment_Method,Order_Status,Delivered_Date,Sales
0,ORD7002,2025-06-30,Anaya,anaya78@gmail.com,9033946351.0,Jaipur,Rajasthan,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0
1,ORD7003,2025-02-03,Arjun,arjun69@gmail.com,9626584853.0,Mumbai,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0
2,ORD7004,2025-05-06,Kavya,kavya92@gmail.com,9118379502.0,Chennai,Tamil Nadu,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0
5,ORD7007,2025-02-10,Kabir,kabir56@gmail.com,9676233869.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0
6,ORD7008,2025-02-17,Aditya,aditya69@gmail.com,9925677930.0,Hyderabad,Telangana,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD7521,2025-02-17,Vihaan,vihaan69@gmail.com,9365147621.0,Bengaluru,Karnataka,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0
520,ORD7522,NaT,Riya,riya63@gmail.com,9275317034.0,Jaipur,Rajasthan,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0
521,ORD7523,2025-04-10,Arjun,arjun38@gmail.com,9897674347.0,Kolkata,West Bengal,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN
522,ORD7524,2025-01-11,Vihaan,vihaan72@gmail.com,9502522302.0,Lucknow,Uttar Pradesh,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0
523,ORD7525,2025-03-03,Arjun,arjun84@gmail.com,9554909075.0,Chennai,Tamil Nadu,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-09-03,2997.0

In [66]:
df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [67]:
df

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,Selling_Price,Discount,Payment_Method,Order_Status,Delivered_Date,Sales,Net_Amount
0,ORD7002,2025-06-30,Anaya,anaya78@gmail.com,9033946351.0,Jaipur,Rajasthan,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.00
1,ORD7003,2025-02-03,Arjun,arjun69@gmail.com,9626584853.0,Mumbai,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0,19996.00
2,ORD7004,2025-05-06,Kavya,kavya92@gmail.com,9118379502.0,Chennai,Tamil Nadu,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0,5697.15
5,ORD7007,2025-02-10,Kabir,kabir56@gmail.com,9676233869.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60
6,ORD7008,2025-02-17,Aditya,aditya69@gmail.com,9925677930.0,Hyderabad,Telangana,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD7521,2025-02-17,Vihaan,vihaan69@gmail.com,9365147621.0,Bengaluru,Karnataka,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00
520,ORD7522,NaT,Riya,riya63@gmail.com,9275317034.0,Jaipur,Rajasthan,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.00
521,ORD7523,2025-04-10,Arjun,arjun38@gmail.com,9897674347.0,Kolkata,West Bengal,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN
522,ORD7524,2025-01-11,Vihaan,vihaan72@gmail.com,9502522302.0,Lucknow,Uttar Pradesh,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.00
523,ORD7525,2025-03-03,Arjun,arjun84@gmail.com,9554909075.0,Chennai,Tamil Nadu,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-09-03,2997.0,2847.15

In [68]:
df['Profit']=df['Net_Amount']*0.20

In [69]:
df['Month']=df['Purchase_Date'].dt.month_name()

In [70]:
df['Year']=df['Purchase_Date'].dt.year

In [71]:
df['Week_Day']=df['Purchase_Date'].dt.day_name()

In [72]:
df

,Transaction_ID,Purchase_Date,Buyer_Name,Email,Phone,City,State,Item_Name,Category,Quantity,...,Discount,Payment_Method,Order_Status,Delivered_Date,Sales,Net_Amount,Profit,Month,Year,Week_Day
0,ORD7002,2025-06-30,Anaya,anaya78@gmail.com,9033946351.0,Jaipur,Rajasthan,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-03-07,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD7003,2025-02-03,Arjun,arjun69@gmail.com,9626584853.0,Mumbai,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-09-02,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD7004,2025-05-06,Kavya,kavya92@gmail.com,9118379502.0,Chennai,Tamil Nadu,Mouse,Electronics,3.0,...,5.0,COD,Returned,2025-08-05,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD7007,2025-02-10,Kabir,kabir56@gmail.com,9676233869.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD7008,2025-02-17,Aditya,aditya69@gmail.com,9925677930.0,Hyderabad,Telangana,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD7521,2025-02-17,Vihaan,vihaan69@gmail.com,9365147621.0,Bengaluru,Karnataka,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0,Monday
520,ORD7522,NaT,Riya,riya63@gmail.com,9275317034.0,Jaipur,Rajasthan,Bottle,Home,2.0,...,0.0,Wallet,Pending,NaT,2998.0,2998.00,599.60,NaN,NaN,NaN
521,ORD7523,2025-04-10,Arjun,arjun38@gmail.com,9897674347.0,Kolkata,West Bengal,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN,NaN,April,2025.0,Thursday
522,ORD7524,2025-01-11,Vihaan,vihaan72@gmail.com,9502522302.0,Lucknow,Uttar Pradesh,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-11,2997.0,2997.00,599.40,January,2025.0,Saturday
523,ORD7525,2025-03-03,Arjun,arjun84@gmail.com,9554909075.0,Chennai,Tamil Nadu,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2025-09-03,2997.0,2847.15,569.43,March,2025.0,Monday

In [73]:
df.isnull().sum()

Transaction_ID     0
Purchase_Date     49
Buyer_Name         0
Email              0
Phone              0
City               0
State              0
Item_Name          0
Category           0
Quantity           0
Selling_Price     39
Discount           0
Payment_Method     0
Order_Status       0
Delivered_Date    33
Sales             39
Net_Amount        39
Profit            39
Month             49
Year              49
Week_Day          49
dtype: int64

In [74]:
df.describe()

,Purchase_Date,Quantity,Selling_Price,Discount,Delivered_Date,Sales,Net_Amount,Profit,Year
count,353,402.000000,363.000000,402.000000,369,363.000000,363.000000,363.000000,353.0
mean,2025-04-02 17:52:51.671388,3.320896,3251.341598,7.823383,2025-05-01 02:00:58.536585,11115.680441,10260.530579,2052.106116,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-02 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.000000,2025-02-17 00:00:00,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,2025-04-19 00:00:00,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,15.000000,2025-06-18 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-12-06 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.460711,3034.218072,7.922703,NaN,12245.226283,11543.812960,2308.762592,0.0

In [75]:
df.to_csv('Ecommerce Sales.csv',index=False)

In [76]:
from sqlalchemy import create_engine

url = URL.create(
    "mysql+pymysql",
    username="root",
    password="Krish@123",
    host="localhost",
    database="ecommerce"
)

engine = create_engine(url)

In [77]:
df.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

402

In [78]:
df.shape

(402, 21)